//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalDietManagerApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dashboard_diet {
            get {
                return ((int)(this["dashboard_diet"]));
            }
            set {
                this["dashboard_diet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dashboard_unit {
            get {
                return ((int)(this["dashboard_unit"]));
            }
            set {
                this["dashboard_unit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int dashboard_kategoria {
            get {
                return ((int)(this["dashboard_kategoria"]));
            }
            set {
                this["dashboard_kategoria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-01-01")]
        public global::System.DateTime dashboard_date {
            get {
                return ((global::System.DateTime)(this["dashboard_date"]));
            }
            set {
                this["dashboard_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_nazwa_sniadanie {
            get {
                return ((string)(this["dashboard_nazwa_sniadanie"]));
            }
            set {
                this["dashboard_nazwa_sniadanie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_sklad_sniadanie {
            get {
                return ((string)(this["dashboard_sklad_sniadanie"]));
            }
            set {
                this["dashboard_sklad_sniadanie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_nazwa_IIsniadanie {
            get {
                return ((string)(this["dashboard_nazwa_IIsniadanie"]));
            }
            set {
                this["dashboard_nazwa_IIsniadanie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_sklad_IIsniadanie {
            get {
                return ((string)(this["dashboard_sklad_IIsniadanie"]));
            }
            set {
                this["dashboard_sklad_IIsniadanie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_nazwa_obiad {
            get {
                return ((string)(this["dashboard_nazwa_obiad"]));
            }
            set {
                this["dashboard_nazwa_obiad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_sklad_obiad {
            get {
                return ((string)(this["dashboard_sklad_obiad"]));
            }
            set {
                this["dashboard_sklad_obiad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_nazwa_podwieczorek {
            get {
                return ((string)(this["dashboard_nazwa_podwieczorek"]));
            }
            set {
                this["dashboard_nazwa_podwieczorek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_sklad_podwieczorek {
            get {
                return ((string)(this["dashboard_sklad_podwieczorek"]));
            }
            set {
                this["dashboard_sklad_podwieczorek"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_nazwa_kolacja {
            get {
                return ((string)(this["dashboard_nazwa_kolacja"]));
            }
            set {
                this["dashboard_nazwa_kolacja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dashboard_sklad_kolacja {
            get {
                return ((string)(this["dashboard_sklad_kolacja"]));
            }
            set {
                this["dashboard_sklad_kolacja"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int template_miasto {
            get {
                return ((int)(this["template_miasto"]));
            }
            set {
                this["template_miasto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int template_dekadowka {
            get {
                return ((int)(this["template_dekadowka"]));
            }
            set {
                this["template_dekadowka"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diet_dieta {
            get {
                return ((int)(this["diet_dieta"]));
            }
            set {
                this["diet_dieta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int diet_miasto {
            get {
                return ((int)(this["diet_miasto"]));
            }
            set {
                this["diet_miasto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int product_produkt {
            get {
                return ((int)(this["product_produkt"]));
            }
            set {
                this["product_produkt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int unit_miasto {
            get {
                return ((int)(this["unit_miasto"]));
            }
            set {
                this["unit_miasto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recepie_nazwa {
            get {
                return ((string)(this["recepie_nazwa"]));
            }
            set {
                this["recepie_nazwa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string recepie_sklad {
            get {
                return ((string)(this["recepie_sklad"]));
            }
            set {
                this["recepie_sklad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int recepie_tab {
            get {
                return ((int)(this["recepie_tab"]));
            }
            set {
                this["recepie_tab"] = value;
            }
        }
    }
}
